import Vue from 'vue'
import {
  Button, Table, Layout, Header, Footer, Sider, Menu, MenuItem, MenuGroup, Icon, Submenu, Message, Breadcrumb, BreadcrumbItem, Card, Dropdown, DropdownItem, DropdownMenu, CellGroup, Cell, Tabs, TabPane, Collapse, Panel, Tree, Form, FormItem, Input, Avatar, Modal, Row, Col, Cascader, Select, Option, DatePicker, AutoComplete, Transfer, Tooltip, Page, CheckboxGroup, Checkbox, InputNumber, Drawer, TimelineItem, Timeline, Divider, Poptip, Upload, Progress, RadioGroup, Radio, Switch, Badge, Tag, Anchor, AnchorLink, Spin, ColorPicker, LoadingBar,
  Alert
} from 'view-design'

import draggable from 'vuedraggable'
import 'viewerjs/dist/viewer.css'
import Viewer from 'v-viewer'

Vue.use(Viewer)
Vue.component('sh-draggable', draggable)

Vue.component('Button', Button)
Vue.component('Table', Table)
Vue.component('Layout', Layout)
Vue.component('Header', Header)
Vue.component('Footer', Footer)
Vue.component('Sider', Sider)
Vue.component('Menu', Menu)
Vue.component('MenuItem', MenuItem)
Vue.component('MenuGroup', MenuGroup)
Vue.component('Icon', Icon)
Vue.component('Submenu', Submenu)
Vue.component('Message', Message)
Vue.component('Breadcrumb', Breadcrumb)
Vue.component('BreadcrumbItem', BreadcrumbItem)
Vue.component('Card', Card)
Vue.component('Dropdown', Dropdown)
Vue.component('DropdownItem', DropdownItem)
Vue.component('DropdownMenu', DropdownMenu)
Vue.component('CellGroup', CellGroup)
Vue.component('Cell', Cell)
Vue.component('Tabs', Tabs)
Vue.component('TabPane', TabPane)
Vue.component('Collapse', Collapse)
Vue.component('Panel', Panel)
Vue.component('Tree', Tree)
Vue.component('Form', Form)
Vue.component('FormItem', FormItem)
Vue.component('Input', Input)
Vue.component('Avatar', Avatar)
Vue.component('Modal', Modal)
Vue.component('Row', Row)
Vue.component('iv-col', Col)
Vue.component('Col', Col)
Vue.component('Cascader', Cascader)
Vue.component('Select', Select)
Vue.component('Option', Option)
Vue.component('DatePicker', DatePicker)
Vue.component('AutoComplete', AutoComplete)
Vue.component('Transfer', Transfer)
Vue.component('Tooltip', Tooltip)
Vue.component('Page', Page)
Vue.component('CheckboxGroup', CheckboxGroup)
Vue.component('Checkbox', Checkbox)
Vue.component('InputNumber', InputNumber)
Vue.component('Drawer', Drawer)
Vue.component('TimelineItem', TimelineItem)
Vue.component('Timeline', Timeline)
Vue.component('Divider', Divider)
Vue.component('Poptip', Poptip)
Vue.component('Upload', Upload)
Vue.component('Progress', Progress)
Vue.component('RadioGroup', RadioGroup)
Vue.component('Radio', Radio)
Vue.component('i-switch', Switch)
Vue.component('Badge', Badge)
Vue.component('Tag', Tag)
Vue.component('Anchor', Anchor)
Vue.component('AnchorLink', AnchorLink)
Vue.component('Spin', Spin)
Vue.component('ColorPicker', ColorPicker)
Vue.component('LoadingBar', LoadingBar)
Vue.component('Alert', Alert)
