<template>
  <Modal
    v-model="changePwdModalStatus"
    mask
    scrollable
    title="修改密码"
    :mask-closable="false"
  >
    <Form
      ref="formInline"
      :model="formInline"
      :rules="ruleInline"
      :label-width="100"
    >
      <FormItem
        prop="oldPass"
        label="旧密码"
        required
        class="account-form-item"
      >
        <Input
          v-model="formInline.oldPass"
          type="password"
          placeholder="输入旧密码"
          password
          @on-keydown.enter="onOkHandle"
        />
      </FormItem>
      <FormItem
        prop="newPass"
        label="新密码"
        required
        class="account-form-item"
      >
        <Input
          v-model="formInline.newPass"
          type="password"
          placeholder="输入新密码"
          password
          @on-keydown.enter="onOkHandle"
        />
      </FormItem>
      <FormItem
        prop="confirmPass"
        label="确认密码"
        required
        class="account-form-item"
      >
        <Input
          v-model="formInline.confirmPass"
          type="password"
          placeholder="输入确认密码"
          password
          @on-keydown.enter="onOkHandle"
        />
      </FormItem>
    </Form>
    <div
      slot="footer"
      class="change-pwd-modal-footer"
    >
      <Button @click="changePwdModalStatus = false">
        取消修改
      </Button>
      <Button
        type="primary"
        :loading="loading"
        @click="onOkHandle"
      >
        修改密码
      </Button>
    </div>
  </Modal>
</template>

<script lang="ts" src="./index.ts"></script>
